application: squaredar
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html
  expiration: 0
  login: required
- url: /processCheckin
  script: sample.py
  login: admin
- url: /calculateNotications
  script: sample.py
  login: admin
- url: /checkin
  script: sample.py
- url: /.*
  script: sample.py
  login: required
